listening-port=3478
listening-ip=0.0.0.0
external-ip=192.168.1.23/0.0.0.0
relay-ip=0.0.0.0
min-port=49152
max-port=49200
realm=localhost
lt-cred-mech
user=test:test123
log-file=stdout
no-tls
no-dtls
verbose
allow-loopback-peers
no-multicast-peers